project:
  type: book

book:
  title: "Spatial-R for Healthy Places"
  author: "Healthy Regions & Policies Lab"
  date: "6/23/2026"
  chapters:
    - index.qmd
    - intro.qmd
    - choropleth.qmd
    - points.qmd
    - access-metrics.qmd
    - spatial-cluster.qmd

bibliography: references.bib

prefer-html: true

format:
  html:
    self-contained: true
    embed-resources: true
    theme:
    - cosmo
    - brand

editor: visual

comments:
  hypothesis: true
