--- 
title: "Intro to Spatial Analysis in R for Health"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This was developed by the Healthy Regions and Policies Lab."
---

## Overview {-}

Measurements of neighborhood ‘social determinants of health’ are increasingly urgent in modern public health thinking, and are thought to drive and/or reinforce social and spatial inequities. Sometimes this necessitates an investigation of neighborhood health patterns, like premature mortality at the census tract scale.

Sometimes we’re interested in area factors like poverty, access to affordable housing, distance to the nearest health provider, or polluting factories and how these factors magnify, moderate, or mediate individual level health. Spatial analysis is an important tool in uncovering the ways in which where people live, work, and play can influence health outcomes. This workshop will present an introduction to spatial analysis, mapping, and GIScience for health applications & spatial epidemiology using the open source R environment. 

During this interactive workshop, participants will be introduced to basic concepts in spatial data analysis, generate thematic maps visualizing neighborhood-level health phenomena, geocode and integrate community resource locations (such as health providers, schools, or sources of pollution) for further exploration, and calculate new spatial access variables. We will review how research questions and hypotheses are updated at each stage of exploratory spatial data analysis. Participants should have a basic understanding of the R environment but no experience is necessary with spatial data or R-spatial libraries.

## Environment Setup {-}

There are multiple resources linked with this workbook. Access the following as needed:

- Data for the workshop: [Zip File](https://github.com/healthyregions/Spatial-Health-Workshop/blob/main/data/Data-2025.zip)
- [Github repository](https://github.com/healthyregions/Spatial-Health-Workshop) of the workshop
- Short link to this workbook: [go.illinois.edu/SpatialR]((https://go.illinois.edu/SpatialR)
- Slide deck for latest workshop: [SER 2026](https://docs.google.com/presentation/d/1WR3-d4IU-WDSVN4oFgFjxbZADtMAExWUBFmqVuvum84/edit?slide=id.gddd9c4a96c_1_138#slide=id.gddd9c4a96c_1_138)

### Software Setup {-}

A basic understanding of R is assumed. This workshop requires several packages, which can be installed from CRAN:

```{r eval=FALSE}
install.packages("sf", "tmap", "tidygeocoder", "rgeoda")
```

For Mac users, check out https://github.com/r-spatial/sf for additional tips if you run into errors when installing the **sf** package. Using homebrew to install **gdal** usually fixes any remaining issues.

Be sure to download the [data](https://github.com/healthyregions/Spatial-Health-Workshop/blob/main/data/Data-2025.zip) in the working directory of your R environment. In the examples, data reside in a folder called "data" of the main working directory.


### Commitment {-}
This workbook is a 3-4 hour, fast-paced overview of mapping, GIScience, and spatial analysis basics for health professionals. When including extensive live coding, support, and additional practice in-person or at home on your own, it can be extended to a week-long program at minimum. You are encouraged to update with your own data finds after each example.

## Background {-}

The workbook is led by Marynia Kolak, Director of the [Healthy Regions & Policies Lab](http://www.healthyregions.org) (HEROP), currently based at the University of Illinois at Urbana-Champaign, and most recently co-facilitated with Ashlynn Wimer (Harvard T. H. Chan). Workshops have been co-facilitated with Qinyun Lin (University of Gothenburg) and Susan Paykin (University of Chicago). 

This suite of tutorials was originally developed for a workshop at the 2021 R-Medicine Conference, and has sinced been updated for multiple workshops at the Society for Epidemiology Research Annual Meeting, and as a workshop at the Institute of Medicine at the University of Gothenburg (Göteborg). 

Some coding snippets & data examples are from the phenomenal team of the [Opioid Environment Toolkit](https://geodacenter.github.io/opioid-environment-toolkit) (Moksha Menghaney, Qinyun Lin, Angela Li), with inspiration from the historic Center for Spatial Data Science training developed by Luc Anselin and Julia Koschinsky at the University of Chicago. 

